import type { TrainingExercise } from '@/types/training';

/** Client-side mirror of the seeded exercise library for offline plan generation. */
export const TRAINING_EXERCISES: TrainingExercise[] = [
  {
    id: 'stop_jumping',
    title: 'Stop Jumping',
    category: 'indoor',
    displayTag: 'PHYSICAL',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Teach your dog to keep four paws on the floor when greeting people.',
    steps: ['Turn away when your dog jumps', 'Reward only when paws stay down', 'Practice with family members'],
    goalTags: ['jumping', 'indoor'],
  },
  {
    id: 'place_training',
    title: 'Place Training',
    category: 'indoor',
    displayTag: 'PHYSICAL',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Send your dog to a mat or bed and reward calm settling.',
    steps: ['Lure onto the mat with a treat', 'Add a verbal cue like Place', 'Increase duration gradually'],
    goalTags: ['indoor', 'anxiety'],
  },
  {
    id: 'sit_stay',
    title: 'Sit & Stay',
    category: 'basic_obedience',
    displayTag: 'MENTAL',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 5,
    description: 'Build impulse control with a reliable sit-stay.',
    steps: ['Ask for sit', 'Hold palm up and wait one second', 'Reward calm stays'],
    goalTags: ['not_listening', 'basic_obedience'],
  },
  {
    id: 'come_when_called',
    title: 'Come When Called',
    category: 'outdoor',
    displayTag: 'OUTDOOR',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 4,
    durationMinutes: 5,
    description: 'Practice recall in a low-distraction area before moving outdoors.',
    steps: ['Say come in a happy tone', 'Reward immediately on arrival', 'Never punish after recall'],
    goalTags: ['outdoor', 'not_listening', 'recall'],
  },
  {
    id: 'loose_leash',
    title: 'Loose Leash Walking',
    category: 'leash_walking',
    displayTag: 'OUTDOOR',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 4,
    durationMinutes: 10,
    description: 'Reward your dog for walking beside you without pulling.',
    steps: ['Stop when the leash tightens', 'Reward when slack returns', 'Change direction to regain focus'],
    goalTags: ['pulling_leash', 'leash_walking'],
  },
  {
    id: 'slow_eating',
    title: 'Slow Eating',
    category: 'eating',
    displayTag: 'MEALTIME',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 5,
    description: 'Use a slow feeder or scatter feeding to prevent gulping.',
    steps: ['Spread kibble on a mat', 'Use a puzzle feeder', 'Pause if eating becomes frantic'],
    goalTags: ['eating_fast', 'eating', 'slow_eating'],
  },
  {
    id: 'wait_before_eating',
    title: 'Wait Before Eating',
    category: 'eating',
    displayTag: 'MEALTIME',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Ask for a brief wait before releasing your pet to their bowl.',
    steps: ['Hold bowl above reach', 'Say wait', 'Release with okay when calm'],
    goalTags: ['eating', 'not_listening'],
  },
  {
    id: 'indoor_potty',
    title: 'Indoor Potty Training',
    category: 'toilet',
    displayTag: 'INDOOR',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 10,
    description: 'Establish a consistent potty routine with frequent breaks.',
    steps: ['Take outside after meals and naps', 'Reward immediately outdoors', 'Avoid scolding accidents'],
    goalTags: ['accidents_indoor', 'toilet'],
  },
  {
    id: 'crate_training',
    title: 'Crate Training',
    category: 'indoor',
    displayTag: 'INDOOR',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 10,
    description: 'Make the crate a safe, positive resting space.',
    steps: ['Feed treats inside the open crate', 'Close door briefly while calm', 'Build duration slowly'],
    goalTags: ['separation', 'indoor', 'anxiety'],
  },
  {
    id: 'leave_it',
    title: 'Leave It',
    category: 'basic_obedience',
    displayTag: 'MENTAL',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Teach your dog to ignore tempting items on cue.',
    steps: ['Cover treat with hand', 'Say leave it', 'Reward when they look away'],
    goalTags: ['not_listening', 'biting'],
  },
  {
    id: 'quiet_on_cue',
    title: 'Quiet on Cue',
    category: 'indoor',
    displayTag: 'MENTAL',
    petTypes: ['dog'],
    difficulty: 'intermediate',
    minAgeMonths: 4,
    durationMinutes: 5,
    description: 'Reward brief moments of silence to reduce excessive barking.',
    steps: ['Wait for a pause in barking', 'Mark quiet with a word', 'Reward calm'],
    goalTags: ['barking', 'indoor'],
  },
  {
    id: 'settle_mat',
    title: 'Settle on Mat',
    category: 'anxiety',
    displayTag: 'MENTAL',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Practice calm relaxation for anxious pets.',
    steps: ['Guide to mat', 'Reward relaxed posture', 'Add gentle petting if enjoyed'],
    goalTags: ['anxiety', 'indoor'],
  },
  {
    id: 'social_greeting',
    title: 'Calm Greeting',
    category: 'socialization',
    displayTag: 'OUTDOOR',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 4,
    durationMinutes: 10,
    description: 'Practice polite greetings with people and dogs from a distance.',
    steps: ['Start at a comfortable distance', 'Reward eye contact', 'Move closer only when calm'],
    goalTags: ['socialization', 'jumping', 'barking'],
  },
  {
    id: 'fetch_focus',
    title: 'Fetch & Focus',
    category: 'outdoor',
    displayTag: 'PHYSICAL',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 10,
    description: 'Burn energy while reinforcing recall and drop-it skills.',
    steps: ['Toss toy a short distance', 'Call back before next throw', 'End while still engaged'],
    goalTags: ['outdoor', 'mental'],
  },
  {
    id: 'trick_shake',
    title: 'Shake Paw',
    category: 'tricks',
    displayTag: 'MENTAL',
    petTypes: ['dog'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'A fun trick that builds engagement and confidence.',
    steps: ['Lure paw lift with treat', 'Add cue shake', 'Reward each successful lift'],
    goalTags: ['tricks', 'mental'],
  },
  {
    id: 'trick_spin',
    title: 'Spin',
    category: 'tricks',
    displayTag: 'MENTAL',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 3,
    durationMinutes: 5,
    description: 'Lure a full circle and add a spin cue.',
    steps: ['Lure nose in a circle', 'Reward completion', 'Fade lure to hand signal'],
    goalTags: ['tricks', 'mental'],
  },
  {
    id: 'cat_target',
    title: 'Target Touch',
    category: 'basic_obedience',
    displayTag: 'MENTAL',
    petTypes: ['cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 5,
    description: 'Teach your cat to touch a target stick or finger.',
    steps: ['Present target near nose', 'Reward touch', 'Move target slightly farther'],
    goalTags: ['not_listening', 'indoor'],
  },
  {
    id: 'cat_carrier',
    title: 'Carrier Comfort',
    category: 'anxiety',
    displayTag: 'INDOOR',
    petTypes: ['cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 10,
    description: 'Help your cat feel safe entering and resting in a carrier.',
    steps: ['Leave carrier open with bedding', 'Toss treats inside', 'Close door briefly when relaxed'],
    goalTags: ['anxiety', 'separation', 'indoor'],
  },
  {
    id: 'structured_play',
    title: 'Structured Play Session',
    category: 'mental',
    displayTag: 'PHYSICAL',
    petTypes: ['dog', 'cat'],
    difficulty: 'beginner',
    minAgeMonths: 2,
    durationMinutes: 15,
    description: 'Short focused play that mixes physical and mental stimulation.',
    steps: ['Use a toy for 2 minutes', 'Pause for a calm break', 'Repeat for the session duration'],
    goalTags: ['mental', 'outdoor', 'indoor'],
  },
  {
    id: 'down_stay',
    title: 'Down & Stay',
    category: 'basic_obedience',
    displayTag: 'MENTAL',
    petTypes: ['dog'],
    difficulty: 'intermediate',
    minAgeMonths: 4,
    durationMinutes: 5,
    description: 'Build duration on a relaxed down position.',
    steps: ['Lure into down', 'Wait two seconds', 'Reward without releasing'],
    goalTags: ['not_listening', 'basic_obedience'],
  },
];
