export type AdminResource = {
  id: string;
  table: string;
  label: string;
  path: string;
  description: string;
  columns: { key: string; label: string; primary?: boolean }[];
  orderBy?: { column: string; ascending?: boolean };
  editableFields?: string[];
  statusField?: string;
  statusOptions?: string[];
};

export const ADMIN_RESOURCES: AdminResource[] = [
  {
    id: 'profiles',
    table: 'profiles',
    label: 'Users',
    path: '/users',
    description: 'App user profiles and signup state',
    columns: [
      { key: 'name', label: 'Name', primary: true },
      { key: 'phone', label: 'Phone' },
      { key: 'city', label: 'City' },
      { key: 'signup_complete', label: 'Signed up' },
      { key: 'is_admin', label: 'Admin' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['name', 'city', 'locality', 'signup_complete', 'is_admin'],
  },
  {
    id: 'pets',
    table: 'pets',
    label: 'Pets',
    path: '/pets',
    description: 'Registered pets',
    columns: [
      { key: 'name', label: 'Name', primary: true },
      { key: 'species', label: 'Species' },
      { key: 'breed', label: 'Breed' },
      { key: 'owner_id', label: 'Owner ID' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['name', 'breed', 'species', 'gender'],
  },
  {
    id: 'adoption_listings',
    table: 'adoption_listings',
    label: 'Adoption listings',
    path: '/adoption/listings',
    description: 'Pets listed for adoption',
    columns: [
      { key: 'pet_name', label: 'Pet', primary: true },
      { key: 'status', label: 'Status' },
      { key: 'city', label: 'City' },
      { key: 'verification_status', label: 'Verification' },
      { key: 'published_at', label: 'Published' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['status', 'verification_status', 'pet_name', 'city', 'description'],
    statusField: 'status',
    statusOptions: ['draft', 'pending_verification', 'active', 'paused', 'adopted', 'removed'],
  },
  {
    id: 'adoption_applications',
    table: 'adoption_applications',
    label: 'Applications',
    path: '/adoption/applications',
    description: 'Adoption applications',
    columns: [
      { key: 'id', label: 'ID', primary: true },
      { key: 'listing_id', label: 'Listing' },
      { key: 'applicant_id', label: 'Applicant' },
      { key: 'status', label: 'Status' },
      { key: 'submitted_at', label: 'Submitted' },
    ],
    orderBy: { column: 'updated_at', ascending: false },
    editableFields: ['status'],
    statusField: 'status',
    statusOptions: [
      'pending',
      'under_review',
      'contacted',
      'meet_and_greet',
      'home_check',
      'approved',
      'adoption_scheduled',
      'completed',
      'rejected',
      'withdrawn',
      'cancelled',
    ],
  },
  {
    id: 'adoption_reports',
    table: 'adoption_reports',
    label: 'Reports',
    path: '/adoption/reports',
    description: 'User reports on listings',
    columns: [
      { key: 'reason', label: 'Reason', primary: true },
      { key: 'listing_id', label: 'Listing' },
      { key: 'reporter_id', label: 'Reporter' },
      { key: 'details', label: 'Details' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['reason', 'details'],
  },
  {
    id: 'community_packs',
    table: 'community_packs',
    label: 'Packs',
    path: '/community/packs',
    description: 'Community packs',
    columns: [
      { key: 'name', label: 'Name', primary: true },
      { key: 'city', label: 'City' },
      { key: 'member_count', label: 'Members' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['name', 'description', 'status', 'city'],
    statusField: 'status',
    statusOptions: ['active', 'archived'],
  },
  {
    id: 'community_meetups',
    table: 'community_meetups',
    label: 'Meetups',
    path: '/community/meetups',
    description: 'Community meetups',
    columns: [
      { key: 'title', label: 'Title', primary: true },
      { key: 'city', label: 'City' },
      { key: 'start_at', label: 'Starts' },
      { key: 'status', label: 'Status' },
    ],
    orderBy: { column: 'start_at', ascending: false },
    editableFields: ['title', 'status', 'city', 'description'],
    statusField: 'status',
    statusOptions: ['upcoming', 'cancelled', 'completed'],
  },
  {
    id: 'global_posts',
    table: 'global_posts',
    label: 'Community posts',
    path: '/community/feed',
    description: 'Global community feed posts',
    columns: [
      { key: 'body', label: 'Body', primary: true },
      { key: 'post_type', label: 'Type' },
      { key: 'author_id', label: 'Author' },
      { key: 'pet_name', label: 'Pet' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['body', 'pet_name', 'post_type'],
  },
  {
    id: 'global_post_reports',
    table: 'global_post_reports',
    label: 'Post reports',
    path: '/community/reports',
    description: 'Flags and reports on community posts',
    columns: [
      { key: 'reason', label: 'Reason', primary: true },
      { key: 'status', label: 'Status' },
      { key: 'post_id', label: 'Post' },
      { key: 'reporter_id', label: 'Reporter' },
      { key: 'details', label: 'Details' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['status', 'reason', 'details'],
    statusField: 'status',
    statusOptions: ['open', 'reviewed', 'dismissed'],
  },
  {
    id: 'pack_posts',
    table: 'pack_posts',
    label: 'Pack posts',
    path: '/community/posts',
    description: 'Posts inside packs',
    columns: [
      { key: 'body', label: 'Body', primary: true },
      { key: 'pack_id', label: 'Pack' },
      { key: 'author_id', label: 'Author' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['body'],
  },
  {
    id: 'community_connections',
    table: 'community_connections',
    label: 'Connections',
    path: '/community/connections',
    description: 'Neighbor connection requests',
    columns: [
      { key: 'requester_id', label: 'Requester', primary: true },
      { key: 'recipient_id', label: 'Recipient' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created' },
    ],
    orderBy: { column: 'created_at', ascending: false },
    editableFields: ['status'],
    statusField: 'status',
    statusOptions: ['pending', 'accepted', 'declined'],
  },
];

export const DASHBOARD_METRICS = ADMIN_RESOURCES.map((r) => ({
  table: r.table,
  label: r.label,
}));
